name: CI

on:
  push:
    branches: [ main, master, daily ]
  pull_request:
    branches: [ main, master, daily ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 1 * * *' # daily at 01:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify
        run: mvn -B verify

      - name: Build
        run: mvn -B -DskipTests=true package

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./target/site/jacoco/jacoco.xml
          flags: unittests
          fail_ci_if_error: false
